Repository fluxcd/flux2, pull requests merged in 2021-10, with the labels that each got.

#1874 Add better checks for reconciliation in reconcile run command
  cmd/flux/reconcile.go
  cmd/flux/reconcile_with_source.go
  cmd/flux/testdata/helmrelease/reconcile_helmrelease_from_git.golden
  cmd/flux/testdata/kustomization/reconcile_kustomization_from_git.golden
Labels: area/UX

#1816 Add Azure E2E tests
  .github/workflows/e2e-azure.yaml
  tests/.gitignore
  tests/azure/README.md
  tests/azure/azure_test.go
  tests/azure/go.mod
  tests/azure/go.sum
  tests/azure/terraform.go
  tests/azure/terraform/aks/.terraform.lock.hcl
  tests/azure/terraform/aks/aks.tf
  tests/azure/terraform/aks/azuredevops.tf
  tests/azure/terraform/aks/event-hub.tf
  tests/azure/terraform/aks/keyvault.tf
  tests/azure/terraform/aks/main.tf
  tests/azure/terraform/aks/outputs.tf
  tests/azure/terraform/aks/service-principal.tf
  tests/azure/terraform/aks/shared.tf
  tests/azure/terraform/shared/.terraform.lock.hcl
  tests/azure/terraform/shared/acr.tf
  tests/azure/terraform/shared/keyvault.tf
  tests/azure/terraform/shared/main.tf
  tests/azure/terraform/shared/outputs.tf
  tests/azure/terraform/shared/service-principal.tf
  tests/azure/terraform/shared/variables.tf
  tests/azure/util_test.go
Labels: area/build

#1855 Add shell completion installation to homebrew formula
  .goreleaser.yml
Labels: area/UX

#1893 Add flux version command
  cmd/flux/version.go
  cmd/flux/version_test.go
  cmd/flux/version_utils.go
  cmd/flux/version_utils_test.go
Labels: area/UX

#1900 Update kustomize-controller API to v1beta2
  .github/workflows/e2e.yaml
  cmd/flux/create_kustomization.go
  cmd/flux/delete_kustomization.go
  cmd/flux/export_kustomization.go
  cmd/flux/get_all.go
  cmd/flux/get_kustomization.go
  cmd/flux/kustomization.go
  cmd/flux/kustomization_test.go
  cmd/flux/main.go
  cmd/flux/reconcile_kustomization.go
  cmd/flux/resume_kustomization.go
  cmd/flux/suspend_kustomization.go
  cmd/flux/trace.go
  cmd/flux/uninstall.go
  go.mod
  go.sum
  internal/bootstrap/bootstrap.go
  internal/bootstrap/bootstrap_plain_git.go
  internal/utils/utils.go
  manifests/bases/kustomize-controller/kustomization.yaml
  pkg/manifestgen/sync/sync.go
  pkg/manifestgen/sync/sync_test.go
  tests/azure/azure_test.go
  tests/azure/util_test.go
Labels: area/kustomization, area/build
