Repository fluxcd/flux2, pull requests merged in 2021-06, with the labels that each got.

#1472 Update go-git to v5.4.2
  go.mod
  go.sum
Labels: area/build, area/git

#1505 Fix yq example for create secret git
  cmd/flux/create_secret_git.go
Labels: area/docs

#1519 Update to Kustomize v4
  go.mod
  go.sum
  pkg/manifestgen/install/manifests.go
  pkg/manifestgen/kustomization/kustomization.go
Labels: area/build

#1534 Allow disabling the deploy key prompt for bootstrap git
  cmd/flux/bootstrap_git.go
Labels: area/bootstrap

#1540 Run conformance tests on ARM64 Kubernetes clusters
  .github/workflows/e2e-arm64.yaml
Labels: area/build, enhancement

#1542 Update source-controller to v0.15.1
  cmd/flux/create_source_helm.go
  go.mod
  go.sum
Labels: area/build, area/helm

#1544 Add create target namespace arg to helmrelease cmd
  cmd/flux/create_helmrelease.go
Labels: area/helm

#1547 Add provisioning script for ARM64 GitHub runners
  .github/runners/README.md
  .github/runners/arm64.sh
  .github/workflows/e2e-arm64.yaml
Labels: area/build

#1553 Add libgit2 test to bootstrap workflow
  .github/workflows/bootstrap.yaml
  .github/workflows/e2e.yaml
Labels: area/build

#1559 Add ARM and ARM64 support to flux GitHub Action
  action/README.md
  action/action.yml
Labels: area/build

#1568 Use image API v1beta1
  cmd/flux/create_image_policy.go
  cmd/flux/create_image_repository.go
  cmd/flux/create_image_update.go
  cmd/flux/delete_image_policy.go
  cmd/flux/delete_image_repository.go
  cmd/flux/delete_image_update.go
  cmd/flux/export_image_policy.go
  cmd/flux/export_image_repository.go
  cmd/flux/export_image_update.go
  cmd/flux/get_image_all.go
  cmd/flux/get_image_policy.go
  cmd/flux/get_image_repository.go
  cmd/flux/get_image_update.go
  cmd/flux/image.go
  cmd/flux/reconcile_image_repository.go
  cmd/flux/reconcile_image_updateauto.go
  cmd/flux/resume_image_repository.go
  cmd/flux/resume_image_updateauto.go
  cmd/flux/suspend_image_repository.go
  cmd/flux/suspend_image_updateauto.go
  internal/utils/utils.go
Labels: area/image-automation

#1555 Implement flux trace command
  .github/workflows/e2e.yaml
  cmd/flux/trace.go
  internal/utils/utils.go
Labels: area/UX, enhancement

#1570 e2e: Update Kubernetes to v1.21.1
  .github/workflows/bootstrap.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e.yaml
Labels: area/build

#1575 fix Control Plane dashboard legend
  manifests/monitoring/grafana/dashboards/control-plane.json
Labels: area/monitoring
