Repository fluxcd/flux2, pull requests merged in 2021-12, with the labels that each got.

#2191 Run the ARM64 e2e tests on Equinix hardware
  .github/runners/README.md
  .github/runners/prereq.sh
  .github/runners/runner-setup.sh
  .github/workflows/e2e-arm64.yaml
Labels: area/build

#2194 monitoring: Pin kube-prometheus-stack to v19.3.0
  manifests/monitoring/kube-prometheus-stack/release.yaml
Labels: area/monitoring

#2195 Removing Kubernetes API Request Duration Graph
  manifests/monitoring/grafana/dashboards/control-plane.json
Labels: area/monitoring

#2153 e2e: Update Calico to v3.20
  .github/workflows/e2e.yaml
Labels: area/build

#2159 cmd: start trace short description with T
  cmd/flux/trace.go
Labels: area/UX

#2208 Update kube-prometheus-stack to 23.2.0
  manifests/monitoring/kube-prometheus-stack/release.yaml
Labels: area/monitoring

#2213 Fix ./manifests/scripts/bundle.sh path resolution
  manifests/scripts/bundle.sh
Labels: area/build

#2223 Add the Helm CLI to the GitHub ARM64 runners setup
  .github/runners/prereq.sh
Labels: area/build

#2212 [RFC-0001] Memorandum on the authorization model
  rfcs/0001-authorization/README.md
Labels: area/RFC
