Repository fluxcd/flux2, pull requests merged in 2021-08, with the labels that each got.

#1672 Adds a watch flag to the get command
  cmd/flux/create_tenant.go
  cmd/flux/get.go
  cmd/flux/get_alert.go
  cmd/flux/get_alertprovider.go
  cmd/flux/get_all.go
  cmd/flux/get_helmrelease.go
  cmd/flux/get_image.go
  cmd/flux/get_image_all.go
  cmd/flux/get_image_policy.go
  cmd/flux/get_image_repository.go
  cmd/flux/get_image_update.go
  cmd/flux/get_kustomization.go
  cmd/flux/get_receiver.go
  cmd/flux/get_source.go
  cmd/flux/get_source_all.go
  cmd/flux/get_source_bucket.go
  cmd/flux/get_source_chart.go
  cmd/flux/get_source_git.go
  cmd/flux/get_source_helm.go
  cmd/flux/main_test.go
  go.sum
  internal/utils/utils.go
Labels: area/UX

#1720 Update links to calendar and resources
  README.md
Labels: area/docs

#1733 Move arm64 e2e to Go tests
  .github/workflows/e2e-arm64.yaml
Labels: area/build
