Repository fluxcd/flux2, pull requests merged in 2021-05, with the labels that each got.

#1380 Migrate the GitOps toolkit links to the new docs website
  README.md
Labels: area/docs

#1381 Update more toolkit.fluxcd.io redirects
  .goreleaser.yml
  CONTRIBUTING.md
  manifests/integrations/registry-credentials-sync/_cronjobs/aws/config-patches.yaml
  manifests/integrations/registry-credentials-sync/aws/config-patches.yaml
Labels: area/docs

#1389 Remove ' command' from Flux CLI docs title
  cmd/flux/docgen.go
Labels: area/docs

#1384 Update go-git-providers to v0.1
  go.mod
  go.sum
Labels: area/bootstrap, area/build

#1391 Update Prometheus labels and dashboard
  manifests/monitoring/grafana/dashboards/control-plane.json
  manifests/monitoring/grafana/deployment.yaml
  manifests/monitoring/prometheus/deployment.yaml
  manifests/monitoring/prometheus/prometheus.yml
Labels: area/monitoring

#1393 Make the Git ref required
  cmd/flux/create_source_git.go
Labels: area/git

#1379 Use proper Host configuration for SSH
  cmd/flux/bootstrap_git.go
Labels: area/bootstrap

#1404 Switch to `crypto/ssh` for parsing of private keys
  cmd/flux/bootstrap_git.go
Labels: area/bootstrap, area/git, bug

#1399 Replace monitoring stack with kube-prometheus-stack
  manifests/monitoring/grafana/dashboards/cluster.json
  manifests/monitoring/grafana/dashboards/control-plane.json
  manifests/monitoring/kube-prometheus-stack/kustomization.yaml
  manifests/monitoring/kube-prometheus-stack/namespace.yaml
  manifests/monitoring/kube-prometheus-stack/release.yaml
  manifests/monitoring/kube-prometheus-stack/repository.yaml
  manifests/monitoring/monitoring-config/kustomization.yaml
  manifests/monitoring/monitoring-config/podmonitor.yaml
Labels: area/monitoring, enhancement

#1412 Enable CRDs upgrade for kube-prometheus-stack
  manifests/monitoring/kube-prometheus-stack/release.yaml
Labels: area/image-automation

#1454 Add GoFish as an install option for Flux CLI
  README.md
Labels: area/docs
