Repository fluxcd/flux2, pull requests merged in 2022-10, with the labels that each got.

#3216 Enable Dependabot for GitHub Actions
  .github/dependabot.yml
Labels: area/build

#3220 Only run e2e tests for Dependabot PRs
  .github/workflows/bootstrap.yaml
  .github/workflows/scan.yaml
Labels: area/build

#3224 Add `diff artifact` command
  cmd/flux/diff_artifact.go
  cmd/flux/diff_artifact_test.go
  cmd/flux/testdata/diff-artifact/deployment-diff.yaml
  cmd/flux/testdata/diff-artifact/deployment.yaml
  cmd/flux/testdata/diff-artifact/success.golden
  go.mod
  go.sum
Labels: enhancement, area/oci

#3231 Adjusted workflow permissions
  .github/workflows/bootstrap.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release-manifests.yml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
Labels: area/build

#3232 Additional workflow permissions tweaks
  .github/workflows/release-manifests.yml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
Labels: area/build

#3236 ci: Refactor GitHub workflows
  .github/workflows/README.md
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release-manifests.yml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
Labels: area/build

#3242 Update dependencies
  Dockerfile
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: dependencies

#3229 RFC-0002: Add Cosign verification for Helm OCI charts
  rfcs/0002-helm-oci/README.md
Labels: area/RFC

#3081 RFC-0004: Block insecure HTTP connections across Flux
  rfcs/0004-insecure-http/README.md
Labels: area/RFC
