Repository fluxcd/flux2, pull requests merged in 2022-01, with the labels that each got.

#2144 Use k8s.io/cli-runtime for kubernetes flags
  cmd/flux/bootstrap_bitbucket_server.go
  cmd/flux/bootstrap_git.go
  cmd/flux/bootstrap_github.go
  cmd/flux/bootstrap_gitlab.go
  cmd/flux/check.go
  cmd/flux/check_test.go
  cmd/flux/completion.go
  cmd/flux/create.go
  cmd/flux/create_alert.go
  cmd/flux/create_alertprovider.go
  cmd/flux/create_helmrelease.go
  cmd/flux/create_image_policy.go
  cmd/flux/create_image_repository.go
  cmd/flux/create_image_update.go
  cmd/flux/create_kustomization.go
  cmd/flux/create_receiver.go
  cmd/flux/create_secret_git.go
  cmd/flux/create_secret_helm.go
  cmd/flux/create_secret_tls.go
  cmd/flux/create_source_bucket.go
  cmd/flux/create_source_git.go
  cmd/flux/create_source_helm.go
  cmd/flux/create_tenant.go
  cmd/flux/delete.go
  cmd/flux/export.go
  cmd/flux/export_secret.go
  cmd/flux/get.go
  cmd/flux/install.go
  cmd/flux/logs.go
  cmd/flux/main.go
  cmd/flux/main_e2e_test.go
  cmd/flux/main_unit_test.go
  cmd/flux/reconcile.go
  cmd/flux/reconcile_alertprovider.go
  cmd/flux/reconcile_receiver.go
  cmd/flux/reconcile_with_source.go
  cmd/flux/resume.go
  cmd/flux/status.go
  cmd/flux/suspend.go
  cmd/flux/trace.go
  cmd/flux/tree_kustomization.go
  cmd/flux/uninstall.go
  cmd/flux/version.go
  go.mod
  internal/bootstrap/bootstrap_plain_git.go
  internal/bootstrap/options.go
  internal/utils/apply.go
  internal/utils/utils.go
Labels: enhancement

#2271 Update toolkit components and packages
  .github/aur/flux-go/PKGBUILD.template
  .github/aur/flux-scm/PKGBUILD.template
  .github/workflows/bootstrap.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/update.yaml
  Dockerfile
  cmd/flux/check_test.go
  cmd/flux/create_source_git_test.go
  cmd/flux/export_test.go
  cmd/flux/helmrelease_test.go
  cmd/flux/image_test.go
  cmd/flux/kustomization_test.go
  cmd/flux/logs_test.go
  cmd/flux/main_e2e_test.go
  cmd/flux/main_unit_test.go
  cmd/flux/trace_test.go
  cmd/flux/tree_kustomization_test.go
  cmd/flux/version_utils_test.go
  go.mod
  go.sum
  internal/bootstrap/git/gogit/gogit_test.go
  internal/flags/crds_test.go
  internal/flags/decryption_provider_test.go
  internal/flags/ecdsa_curve_test.go
  internal/flags/git_implementation_test.go
  internal/flags/helm_chart_source_test.go
  internal/flags/helm_release_values_test.go
  internal/flags/kustomization_source_test.go
  internal/flags/log_level_test.go
  internal/flags/public_key_algorithm_test.go
  internal/flags/rsa_key_bits_test.go
  internal/flags/safe_relative_path_test.go
  internal/flags/source_bucket_provider_test.go
  internal/utils/utils_test.go
  manifests/bases/helm-controller/kustomization.yaml
  manifests/bases/image-automation-controller/kustomization.yaml
  manifests/bases/image-reflector-controller/kustomization.yaml
  manifests/bases/kustomize-controller/kustomization.yaml
  manifests/bases/source-controller/kustomization.yaml
  manifests/crds/kustomization.yaml
  pkg/manifestgen/sourcesecret/sourcesecret_test.go
  pkg/manifestgen/sync/sync_test.go
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#2272 Update golang.org/x/crypto to latest main
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#2280 Update Git providers
  Makefile
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#2281 Add optional bindir input to Flux GitHub Action
  action/action.yml
Labels: area/install

#2234 Use provided SSH hostname to sync with SSH
  internal/bootstrap/bootstrap_provider.go
Labels: area/bootstrap

#2285 Update go-git-provider to fix GitLab bootstrap regression bug
  go.mod
  go.sum
Labels: area/bootstrap

#2231 Fix port overwrite for `flux bootstrap git`
  cmd/flux/bootstrap_git.go
Labels: bug, area/git, area/bootstrap

#2288 Fix makefile envtest setup and usage
  .github/workflows/e2e.yaml
  .gitignore
  Makefile
Labels: area/build

#2267 Add git build dependency to flux-scm
  .github/aur/flux-scm/PKGBUILD.template
Labels: area/build

#2141 Simplify arguments of flux trace command
  cmd/flux/trace.go
  cmd/flux/trace_test.go
Labels: enhancement

#2290 Update dependencies
  cmd/flux/status.go
  cmd/flux/tree_kustomization.go
  go.mod
  go.sum
  internal/utils/apply.go
  pkg/status/status.go
Labels: area/build

#2294 Improve the bootstrap e2e test workflow
  .github/workflows/bootstrap.yaml
Labels: area/build

#2296 Fix Archlinux PKGBUILD check() run on ARM
  .github/aur/flux-go/PKGBUILD.template
  .github/aur/flux-scm/PKGBUILD.template
Labels: area/build

#2295 Publish Flux Software Bill of Materials (SBOM)
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: area/build

#2300 Fix Azure e2e tests and GoReleaser buildx directive
  .goreleaser.yml
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#2301 Sign the release artifacts checksums and images
  .github/workflows/release.yaml
  .goreleaser.yml
Labels: area/build

#2304 ci: Fix release notes generator
  .github/workflows/release.yaml
Labels: area/build

#2305 Update kubectl to 1.23.1 in flux-cli container image
  Dockerfile
Labels: area/build

#2297 Shorten Git SHA commit in `flux get` commands output
  cmd/flux/get_kustomization.go
  cmd/flux/get_source_git.go
  cmd/flux/testdata/kustomization/get_kustomization_from_git.golden
Labels: area/UX, area/git, area/kustomization

#2167 Preview local changes with flux build/diff kustomization
  cmd/flux/build.go
  cmd/flux/build_kustomization.go
  cmd/flux/build_kustomization_test.go
  cmd/flux/diff.go
  cmd/flux/diff_kustomization.go
  cmd/flux/diff_kustomization_test.go
  cmd/flux/main_test.go
  cmd/flux/testdata/build-kustomization/delete-service/deployment.yaml
  cmd/flux/testdata/build-kustomization/delete-service/hpa.yaml
  cmd/flux/testdata/build-kustomization/delete-service/kustomization.yaml
  cmd/flux/testdata/build-kustomization/podinfo-kustomization.yaml
  cmd/flux/testdata/build-kustomization/podinfo-result.yaml
  cmd/flux/testdata/build-kustomization/podinfo-source.yaml
  cmd/flux/testdata/build-kustomization/podinfo-without-service-result.yaml
  cmd/flux/testdata/build-kustomization/podinfo/deployment.yaml
  cmd/flux/testdata/build-kustomization/podinfo/hpa.yaml
  cmd/flux/testdata/build-kustomization/podinfo/kustomization.yaml
  cmd/flux/testdata/build-kustomization/podinfo/service.yaml
  cmd/flux/testdata/build-kustomization/podinfo/token.encrypted
  cmd/flux/testdata/diff-kustomization/deployment.yaml
  cmd/flux/testdata/diff-kustomization/diff-with-deployment.golden
  cmd/flux/testdata/diff-kustomization/diff-with-drifted-key-sops-secret.golden
  cmd/flux/testdata/diff-kustomization/diff-with-drifted-secret.golden
  cmd/flux/testdata/diff-kustomization/diff-with-drifted-service.golden
  cmd/flux/testdata/diff-kustomization/diff-with-drifted-value-sops-secret.golden
  cmd/flux/testdata/diff-kustomization/key-sops-secret.yaml
  cmd/flux/testdata/diff-kustomization/kustomization.yaml
  cmd/flux/testdata/diff-kustomization/nothing-is-deployed.golden
  cmd/flux/testdata/diff-kustomization/secret.yaml
  cmd/flux/testdata/diff-kustomization/service.yaml
  cmd/flux/testdata/diff-kustomization/value-sops-secret.yaml
  go.mod
  go.sum
  internal/build/build.go
  internal/build/build_test.go
  internal/build/diff.go
Labels: enhancement, area/UX, area/kustomization

#2316 [security] Enable pod security warnings for flux-system
  manifests/install/namespace.yaml
  pkg/manifestgen/install/templates.go
Labels: area/bootstrap, area/install

#2336 Upgrade go-git-providers to v0.5.3
  go.mod
  go.sum
Labels: bug, area/bootstrap

#2342 Run the CLI as non-root
  Dockerfile
Labels: area/build

#2343 Set minimum supported version to Kubernetes 1.20.6
  .github/workflows/e2e.yaml
  CONTRIBUTING.md
  cmd/flux/check.go
  cmd/flux/testdata/check/check_pre.golden
Labels: area/install

#2347 Fix output usage for `flux get <sources|images>`
  cmd/flux/get_image.go
  cmd/flux/get_source.go
Labels: area/UX

#2348 Add pkg-config to arm runners
  .github/runners/prereq.sh
Labels: area/build

#2356 Adapt diff test to match Kubernetes 1.23.3 API response
  cmd/flux/testdata/diff-kustomization/diff-with-drifted-service.golden
Labels: area/build
