Repository fluxcd/flux2, pull requests merged in 2022-05, with the labels that each got.

#2651 kustomize: use FS from `fluxcd/pkg`
  go.mod
  go.sum
  internal/bootstrap/bootstrap_plain_git.go
  internal/build/build.go
  pkg/manifestgen/install/manifests.go
  pkg/manifestgen/kustomization/kustomization.go
  pkg/manifestgen/kustomization/options.go
Labels: area/bootstrap, area/install, area/kustomization

#2698 Update dependencies
  .github/runners/prereq.sh
  Dockerfile
  go.mod
  go.sum
Labels: area/build

#2700 MacOS: fix bootstrap manifest generation
  pkg/manifestgen/install/manifests.go
Labels: area/bootstrap

#2701 Grant service account read-only access to controllers
  manifests/rbac/controller.yaml
Labels: area/image-automation

#2703 Modify tmp dir generation to be absolute on all OSes
  cmd/flux/bootstrap.go
  cmd/flux/bootstrap_bitbucket_server.go
  cmd/flux/bootstrap_git.go
  cmd/flux/bootstrap_github.go
  cmd/flux/bootstrap_gitlab.go
  cmd/flux/install.go
  pkg/manifestgen/install/install.go
  pkg/manifestgen/install/manifests.go
  pkg/manifestgen/tmpdir.go
Labels: bug, area/bootstrap

#2748 fix e2e tests
  cmd/flux/check_test.go
Labels: bug

#2747 Move MAINTAINERS to f/community
  MAINTAINERS
Labels: area/docs

#2769 Update Go to 1.18 in CI
  .github/workflows/bootstrap.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e.yaml
  .github/workflows/rebase.yaml
  .github/workflows/release.yaml
  .github/workflows/update.yaml
  Dockerfile
Labels: area/build

#2727 grafana: display exported ns, slight resizing, default sorting by state
  manifests/monitoring/grafana/dashboards/cluster.json
Labels: enhancement, area/monitoring

#2773 Update dependencies
  .github/workflows/bootstrap.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
  go.mod
  go.sum
  pkg/manifestgen/sourcesecret/sourcesecret.go
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#2778 Update go-git-providers to v0.6.0
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#2767 Add `--ignore-paths` flag to `flux create source (git|bucket)`
  cmd/flux/create_source_bucket.go
  cmd/flux/create_source_git.go
  cmd/flux/create_source_git_test.go
  cmd/flux/testdata/create_source_git/export.golden
Labels: area/UX, area/source

#2782 Refactor Flux Prometheus monitoring stack
  manifests/monitoring/grafana/datasources.yaml
  manifests/monitoring/grafana/deployment.yaml
  manifests/monitoring/grafana/kustomization.yaml
  manifests/monitoring/grafana/providers.yaml
  manifests/monitoring/grafana/service.yaml
  manifests/monitoring/kube-prometheus-stack/namespace.yaml
  manifests/monitoring/kube-prometheus-stack/release.yaml
  manifests/monitoring/kube-prometheus-stack/repository.yaml
  manifests/monitoring/kustomization.yaml
  manifests/monitoring/monitoring-config/dashboards/cluster.json
  manifests/monitoring/monitoring-config/dashboards/control-plane.json
  manifests/monitoring/monitoring-config/kustomization.yaml
  manifests/monitoring/monitoring-config/podmonitor.yaml
  manifests/monitoring/prometheus/account.yaml
  manifests/monitoring/prometheus/deployment.yaml
  manifests/monitoring/prometheus/kustomization.yaml
  manifests/monitoring/prometheus/prometheus.yml
  manifests/monitoring/prometheus/rbac.yaml
  manifests/monitoring/prometheus/service.yaml
Labels: area/monitoring
