Repository fluxcd/flux2, pull requests merged in 2022-02, with the labels that each got.

#2368 Update dependencies
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#2375 Add contextual error code for flux diff kustomization
  cmd/flux/diff.go
  cmd/flux/diff_kustomization.go
  cmd/flux/main.go
  cmd/flux/main_test.go
  internal/build/diff.go
Labels: enhancement

#2376 e2e: Fix Azure image update automation test
  tests/azure/azure_test.go
Labels: bug, area/build

#2364 Add GPG signing to Github/Gitlab/Bitbucket bootstrap
  cmd/flux/bootstrap_bitbucket_server.go
  cmd/flux/bootstrap_github.go
  cmd/flux/bootstrap_gitlab.go
Labels: enhancement, area/bootstrap

#2377 Fix `flux build/diff` when parsing SOPS encrypted secrets
  internal/build/build.go
  internal/build/build_test.go
Labels: bug, area/diff

#2380 Fix panic on bootstrap when orgRef is not retrieved
  internal/bootstrap/bootstrap_provider.go
Labels: bug, area/bootstrap

#2382 Use `client.Patch` for suspend/resume operations
  cmd/flux/resume.go
  cmd/flux/suspend.go
Labels: enhancement

#2389 Fix wrong deletion message on flux diff
  go.mod
  internal/build/diff.go
Labels: bug, area/diff

#2397 Fix bootstrap CRD wait race condition
  go.mod
  go.sum
Labels: area/bootstrap

#2415 Add GitRepository namespace arg to `flux create image update`
  cmd/flux/create_image_update.go
Labels: enhancement, area/image-automation

#2418 Fix bootstrap: Reset schema cache after applying CRDs
  go.mod
  go.sum
  internal/utils/apply.go
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/bootstrap

#2425 Add a simple spinner when running flux diff kustomization
  go.mod
  go.sum
  internal/build/diff.go
Labels: area/UX, area/diff

#2427 Bootstrap bitbucket-server: Make sure we retrieve the right project
  go.mod
  go.sum
Labels: bug, area/bootstrap

#2426 Add support for Kustomizations with dot-prefixed paths
  internal/flags/safe_relative_path.go
  internal/flags/safe_relative_path_test.go
Labels: area/git, area/bootstrap, area/kustomization

#2443 Validate that object name adheres to RFC 1123 for `flux create` commands
  cmd/flux/create.go
  cmd/flux/create_alert.go
  cmd/flux/create_alertprovider.go
  cmd/flux/create_helmrelease.go
  cmd/flux/create_image_policy.go
  cmd/flux/create_image_repository.go
  cmd/flux/create_image_update.go
  cmd/flux/create_kustomization.go
  cmd/flux/create_receiver.go
  cmd/flux/create_secret_git.go
  cmd/flux/create_secret_git_test.go
  cmd/flux/create_secret_helm.go
  cmd/flux/create_secret_helm_test.go
  cmd/flux/create_secret_tls.go
  cmd/flux/create_secret_tls_test.go
  cmd/flux/create_source_bucket.go
  cmd/flux/create_source_git.go
  cmd/flux/create_source_git_test.go
  cmd/flux/create_source_helm.go
  cmd/flux/create_tenant.go
  cmd/flux/create_test.go
Labels: enhancement

#2452 Diff: fix stringData Secret issue
  cmd/flux/diff_kustomization.go
  cmd/flux/diff_kustomization_test.go
  cmd/flux/testdata/build-kustomization/podinfo-result.yaml
  cmd/flux/testdata/diff-kustomization/diff-with-drifted-stringdata-sops-secret.golden
  cmd/flux/testdata/diff-kustomization/stringdata-sops-secret.yaml
  go.mod
  go.sum
  internal/build/build.go
  internal/build/diff.go
  internal/utils/apply.go
  pkg/status/status.go
Labels: area/diff

#2448 Use `metadata.Client` for reconcile operations
  cmd/flux/alert.go
  cmd/flux/alert_provider.go
  cmd/flux/helmrelease.go
  cmd/flux/image.go
  cmd/flux/kustomization.go
  cmd/flux/object.go
  cmd/flux/receiver.go
  cmd/flux/reconcile.go
  cmd/flux/reconcile_with_source.go
  cmd/flux/source.go
  cmd/flux/testdata/helmrelease/delete_helmrelease_from_git.golden
  cmd/flux/testdata/helmrelease/resume_helmrelease_from_git.golden
  cmd/flux/testdata/helmrelease/suspend_helmrelease_from_git.golden
  cmd/flux/testdata/kustomization/delete_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/resume_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/suspend_kustomization_from_git.golden
Labels: enhancement

#2450 Add `--wait` flag to flux `resume` cmd
  cmd/flux/resume.go
Labels: enhancement, area/UX

#2440 Add e2e sequence diagrams
  docs/internal/diagrams.md
Labels: area/docs

#2467 Update `get` subcommand column order
  CONTRIBUTING.md
  Makefile
  cmd/flux/get_alert.go
  cmd/flux/get_helmrelease.go
  cmd/flux/get_image_policy.go
  cmd/flux/get_image_repository.go
  cmd/flux/get_image_update.go
  cmd/flux/get_kustomization.go
  cmd/flux/get_receiver.go
  cmd/flux/get_source_bucket.go
  cmd/flux/get_source_chart.go
  cmd/flux/get_source_git.go
  cmd/flux/get_source_helm.go
  cmd/flux/main_test.go
  cmd/flux/testdata/helmrelease/get_helmrelease_from_git.golden
  cmd/flux/testdata/image/get_image_policy_regex.golden
  cmd/flux/testdata/image/get_image_policy_semver.golden
  cmd/flux/testdata/kustomization/get_kustomization_from_git.golden
Labels: area/UX
