Repository fluxcd/flux2, pull requests merged in 2022-12, with the labels that each got.

#3377 bootstrap: fallback to default known_hosts
  cmd/flux/bootstrap_bitbucket_server.go
  cmd/flux/bootstrap_git.go
  cmd/flux/bootstrap_github.go
  cmd/flux/bootstrap_gitlab.go
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/git

#3403 Use proper file paths in Azure e2e tests
  tests/azure/azure_test.go
  tests/azure/util_test.go
Labels: area/build

#3389 Push/Build artifacts from stdin
  cmd/flux/build_artifact.go
  cmd/flux/push_artifact.go
  go.mod
  go.sum
Labels: area/oci

#3413 Update dependencies
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#3415 Fix dry-run still loading kubeconfig issue
  cmd/flux/build_kustomization.go
  cmd/flux/testdata/build-kustomization/delete-service/hpa.yaml
  cmd/flux/testdata/build-kustomization/podinfo-result.yaml
  cmd/flux/testdata/build-kustomization/podinfo-without-service-result.yaml
  cmd/flux/testdata/build-kustomization/podinfo/hpa.yaml
  internal/build/build.go
Labels: bug, area/diff

#3424 build: Revert sigstore/cosign-installer to v2.8.1
  .github/workflows/release.yaml
Labels: area/build

#3418 Fix path on `flux push`
  cmd/flux/build_artifact.go
  cmd/flux/build_artifact_test.go
  cmd/flux/push_artifact.go
Labels: area/oci

#3427 Update dependencies
  .github/workflows/e2e.yaml
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#3441 check: Show the latest stored version of CRDs
  cmd/flux/check.go
Labels: bug, area/UX
