Repository fluxcd/flux2, pull requests merged in 2022-03, with the labels that each got.

#2512 Introduce a printer interface for flux resources
  cmd/flux/get.go
  internal/build/diff.go
  internal/utils/utils.go
  pkg/printers/dyff.go
  pkg/printers/interface.go
  pkg/printers/table_printer.go
Labels: area/UX

#2530 Add components-extra example usage to CLI help
  cmd/flux/bootstrap.go
  cmd/flux/install.go
Labels: area/docs

#2564 Use absolute domain name for the events address
  manifests/bases/helm-controller/patch.yaml
  manifests/bases/image-automation-controller/patch.yaml
  manifests/bases/image-reflector-controller/patch.yaml
  manifests/bases/kustomize-controller/patch.yaml
  manifests/bases/source-controller/patch.yaml
  pkg/manifestgen/install/manifests.go
Labels: enhancement, area/bootstrap, area/install

#2565 fix: wait for Source objects observed generation
  cmd/flux/create_source_bucket.go
  cmd/flux/create_source_git.go
  cmd/flux/create_source_git_test.go
  cmd/flux/create_source_helm.go
  cmd/flux/reconcile_source_bucket.go
  go.mod
  go.sum
Labels: bug, area/UX, area/source

#2566 Fix resume source bucket panic
  cmd/flux/resume_source_bucket.go
Labels: bug

#2572 Add the kube client qps and burst to the global args
  cmd/flux/bootstrap_bitbucket_server.go
  cmd/flux/bootstrap_git.go
  cmd/flux/bootstrap_github.go
  cmd/flux/bootstrap_gitlab.go
  cmd/flux/build_kustomization.go
  cmd/flux/check.go
  cmd/flux/completion.go
  cmd/flux/create.go
  cmd/flux/create_alert.go
  cmd/flux/create_alertprovider.go
  cmd/flux/create_helmrelease.go
  cmd/flux/create_kustomization.go
  cmd/flux/create_receiver.go
  cmd/flux/create_secret_git.go
  cmd/flux/create_secret_helm.go
  cmd/flux/create_secret_tls.go
  cmd/flux/create_source_bucket.go
  cmd/flux/create_source_git.go
  cmd/flux/create_source_helm.go
  cmd/flux/create_tenant.go
  cmd/flux/delete.go
  cmd/flux/diff_kustomization.go
  cmd/flux/diff_kustomization_test.go
  cmd/flux/export.go
  cmd/flux/export_secret.go
  cmd/flux/get.go
  cmd/flux/install.go
  cmd/flux/logs.go
  cmd/flux/main.go
  cmd/flux/reconcile.go
  cmd/flux/reconcile_alertprovider.go
  cmd/flux/reconcile_receiver.go
  cmd/flux/reconcile_with_source.go
  cmd/flux/resume.go
  cmd/flux/suspend.go
  cmd/flux/trace.go
  cmd/flux/tree_kustomization.go
  cmd/flux/uninstall.go
  cmd/flux/version.go
  go.mod
  go.sum
  internal/bootstrap/bootstrap_plain_git.go
  internal/bootstrap/options.go
  internal/build/build.go
  internal/utils/apply.go
  internal/utils/utils.go
Labels: enhancement

#2534 Add coreutils (for Mac OS) as a dependency
  CONTRIBUTING.md
Labels: area/docs

#2584 Diff: Update homeport/Dyff to v1.5.2
  go.mod
  go.sum
Labels: area/diff
