Repository fluxcd/flux2, pull requests merged in 2023-01, with the labels that each got.

#3477 fix(install-script): support $GITHUB_TOKEN
  install/README.md
  install/flux.sh
Labels: area/install

#3501 Add GITHUB_TOKEN to Flux GitHub Action
  action/README.md
  action/action.yml
Labels: enhancement

#3532 Update Alpine to v3.17 and kubectl to v1.26.1 in flux-cli image
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  Dockerfile
Labels: area/build

#3507 Update prometheus-community helm repo due to the suspension of OCI builds
  manifests/monitoring/kube-prometheus-stack/release.yaml
  manifests/monitoring/kube-prometheus-stack/repository.yaml
Labels: area/monitoring

#3537 Update dependencies to Kubernetes v1.26.1
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: dependencies

#3540 Add json/yaml output to flux push artifact
  action/README.md
  cmd/flux/push_artifact.go
Labels: enhancement, area/oci

#3542 flux tree: Add namespaces to objects reconciled from HRs
  cmd/flux/tree_kustomization.go
  internal/utils/objectutil.go
  internal/utils/utils.go
Labels: area/UX
