Repository fluxcd/flux2, pull requests merged in 2023-08, with the labels that each got.

#4126 Set Kubernetes min version to 1.25
  cmd/flux/check.go
  cmd/flux/testdata/check/check_pre.golden
Labels: area/install

#4131 Fix selection of kustomization resource from multi doc yaml
  cmd/flux/diff_kustomization_test.go
  cmd/flux/testdata/diff-kustomization/flux-kustomization-multiobj.yaml
  internal/build/build.go
  internal/build/build_test.go
  internal/build/testdata/local-kustomization/invalid-resource.yaml
Labels: area/diff

#4140 Disable azure e2e test
  .github/workflows/e2e-azure.yaml
Labels: area/ci

#4151 ci: enable security-and-quality CodeQL query
  .github/workflows/scan.yaml
Labels: area/ci

#4166 e2e: Add Kubernetes v1.28.0 to conformance tests
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
Labels: area/testing

#4175 build: update securejoin dependency
  go.mod
  go.sum
Labels: dependencies

#4176 ci: disable fail-fast for ARM end-to-end
  .github/workflows/e2e-arm64.yaml
  cmd/flux/main_e2e_test.go
Labels: area/ci

#4177 Set min value for the `--ssh-rsa-bits` flag
  internal/flags/rsa_key_bits.go
  internal/flags/rsa_key_bits_test.go
Labels: area/git, area/bootstrap

#4180 Fix controller version info
  cmd/flux/version.go
  cmd/flux/version_test.go
Labels: bug

#4183 Fix autocompletion for helm chart
  cmd/flux/reconcile_source_chart.go
Labels: area/ux

#4189 Update dependencies
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: dependencies

#4169 Add monitoring configuration deprecation notice
  manifests/monitoring/README.md
Labels: area/monitoring

#4197 Fix links to fluxcd.io
  README.md
  action/README.md
Labels: area/docs
