Repository fluxcd/flux2, pull requests merged in 2023-02, with the labels that each got.

#3549 flux tree: Track CRDs managed by HelmReleases
  cmd/flux/tree_kustomization.go
Labels: area/UX

#3575 RFC-0003: Introduce Flux OCI media type
  rfcs/0003-kubernetes-oci/README.md
Labels: area/RFC

#3592 tests: only provide template values when used
  cmd/flux/build_artifact_test.go
  cmd/flux/build_kustomization_test.go
  cmd/flux/diff_kustomization_test.go
  cmd/flux/export_test.go
  cmd/flux/helmrelease_test.go
  cmd/flux/image_test.go
  cmd/flux/install_test.go
  cmd/flux/kustomization_test.go
  cmd/flux/main_e2e_test.go
  cmd/flux/source_oci_test.go
  internal/utils/utils_test.go
Labels: area/build

#3566 rbac: Add view and edit aggregated cluster roles
  manifests/bases/helm-controller/kustomization.yaml
  manifests/bases/image-automation-controller/kustomization.yaml
  manifests/bases/image-reflector-controller/kustomization.yaml
  manifests/bases/kustomize-controller/kustomization.yaml
  manifests/bases/notification-controller/kustomization.yaml
  manifests/bases/source-controller/kustomization.yaml
  manifests/rbac/edit.yaml
  manifests/rbac/kustomization.yaml
  manifests/rbac/view.yaml
Labels: area/UX, area/bootstrap, area/install, area/security

#3601 ci: Fix Snyk Go build VCS stamping error
  .github/workflows/scan.yaml
Labels: area/build

#3602 Update source-controller to v0.35.1
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  action/README.md
  cmd/flux/push_artifact.go
  cmd/flux/testdata/helmrelease/create_source_git.golden
  cmd/flux/testdata/helmrelease/reconcile_helmrelease_from_git.golden
  cmd/flux/testdata/kustomization/create_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/create_source_git.golden
  cmd/flux/testdata/kustomization/get_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/reconcile_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/resume_kustomization_from_git.golden
  cmd/flux/testdata/oci/create_source_oci.golden
  cmd/flux/testdata/oci/get_oci.golden
  cmd/flux/testdata/oci/reconcile_oci.golden
  cmd/flux/testdata/oci/resume_oci.golden
  cmd/flux/testdata/trace/deployment.golden
  cmd/flux/testdata/trace/deployment.yaml
  cmd/flux/testdata/trace/helmrelease-oci.golden
  cmd/flux/testdata/trace/helmrelease-oci.yaml
  cmd/flux/testdata/trace/helmrelease.golden
  cmd/flux/testdata/trace/helmrelease.yaml
  cmd/flux/testdata/tree/kustomizations.yaml
  go.mod
  go.sum
  manifests/bases/source-controller/kustomization.yaml
  manifests/crds/kustomization.yaml
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_plain_git.go
  rfcs/0003-kubernetes-oci/README.md
  tests/azure/go.mod
  tests/azure/go.sum
Labels: enhancement, area/source, area/build, area/RFC, area/oci

#3604 build: convert ::set-output to $GITHUB_OUTPUT
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/release.yaml
  .github/workflows/update.yaml
Labels: area/build

#3605 build: ensure newlines work with $GITHUB_OUTPUT
  .github/workflows/update.yaml
Labels: area/build

#3606 build: further solve issue release workflow
  .github/workflows/update.yaml
Labels: area/build

#3610 Update dependencies
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#3578 Add command to print the reconcilers status
  cmd/flux/stats.go
Labels: enhancement, area/UX

#3615 Update implementation history of RFC-0003 and RFC-0005
  rfcs/0003-kubernetes-oci/README.md
  rfcs/0005-artifact-revision-and-digest/README.md
Labels: area/RFC

#3626 Update dependencies
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#3645 Update dependencies
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build
