Repository fluxcd/flux2, pull requests merged in 2023-09, with the labels that each got.

#4226 Update description of kubeconfig specific flag
  cmd/flux/main.go
Labels: area/ux, backport:release/v2.1.x

#4255 tests/azure: update controller dependencies
  tests/azure/go.mod
  tests/azure/go.sum
Labels: dependencies, backport:release/v2.1.x

#4228 Improve AUR package templates
  .github/aur/flux-bin/.SRCINFO.template
  .github/aur/flux-bin/PKGBUILD.template
Labels: area/ci, backport:release/v2.1.x

#4285 Add badge for SLSA Level 3
  README.md
Labels: area/docs
