Repository fluxcd/flux2, pull requests merged in 2023-12, with the labels that each got.

#4463 Update Git dependencies
  go.mod
  go.sum
  tests/azure/azure_test.go
  tests/azure/go.mod
  tests/azure/go.sum
  tests/integration/azure_specific_test.go
  tests/integration/go.mod
  tests/integration/go.sum
Labels: area/git, dependencies

#4437 Add force and reset flags to `flux reconcile hr`
  cmd/flux/create_helmrelease.go
  cmd/flux/create_kustomization.go
  cmd/flux/delete_helmrelease.go
  cmd/flux/events.go
  cmd/flux/events_test.go
  cmd/flux/export_helmrelease.go
  cmd/flux/get_all.go
  cmd/flux/get_helmrelease.go
  cmd/flux/helmrelease.go
  cmd/flux/reconcile.go
  cmd/flux/reconcile_helmrelease.go
  cmd/flux/resume_helmrelease.go
  cmd/flux/stats.go
  cmd/flux/suspend_helmrelease.go
  cmd/flux/testdata/export/helm-release.yaml
  cmd/flux/testdata/export/objects.yaml
  cmd/flux/testdata/trace/deployment.yaml
  cmd/flux/testdata/trace/helmrelease-oci.yaml
  cmd/flux/testdata/trace/helmrelease.yaml
  cmd/flux/trace.go
  cmd/flux/trace_test.go
  cmd/flux/tree_kustomization.go
  internal/flags/crds.go
  internal/utils/objectutil.go
  internal/utils/utils.go
  pkg/uninstall/uninstall.go
  tests/azure/go.mod
  tests/azure/go.sum
  tests/azure/util_test.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/oci_test.go
  tests/integration/suite_test.go
Labels: area/helm

#4317 Correct "sync" to "component" in log lines
  pkg/bootstrap/bootstrap_plain_git.go
Labels: area/bootstrap

#4464 updating go-git-providers to v0.19.2
  go.mod
  go.sum
Labels: area/bootstrap, dependencies

#4468 Add 2.2.x backport label
  .github/labels.yaml
Labels: area/ci

#4476 Properly detect unsupported API errors
  cmd/flux/get.go
  cmd/flux/get_all.go
  cmd/flux/get_source_all.go
Labels: bug, backport:release/v2.2.x

#4481 Remove duplicate part of the reconcile hr --reset help message
  cmd/flux/reconcile_helmrelease.go
Labels: backport:release/v2.2.x

#4484 Run conformance tests for Kubernetes v1.29.0
  .github/workflows/e2e-arm64.yaml
Labels: area/testing, backport:release/v2.2.x

#4488 tests: update API dependencies
  tests/azure/go.mod
  tests/azure/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies, backport:release/v2.2.x

#4499 Fix typo in Git bootstrap
  pkg/bootstrap/bootstrap_plain_git.go
Labels: backport:release/v2.2.x

#4505 Update helm-controller to v0.37.2 in tests
  tests/azure/go.mod
  tests/azure/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: backport:release/v2.2.x
