Repository fluxcd/flux2, pull requests merged in 2023-10, with the labels that each got.

#4323 e2e: Update Go dependencies
  tests/azure/go.mod
  tests/azure/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies, area/testing, backport:release/v2.1.x

#4296 fix: only wait for changeset if the result is not empty
  internal/utils/apply.go
Labels: backport:release/v2.1.x

#4284 Make `flux pull` work for OCI artifacts produced by other tools
  cmd/flux/pull_artifact.go
  go.mod
  go.sum
Labels: area/oci, area/ux, backport:release/v2.1.x

#4332 Add CLI flags for OCIRepository signature verification
  cmd/flux/create_source_oci.go
  cmd/flux/create_source_oci_test.go
  cmd/flux/testdata/oci/export_with_verify_secret.golden
  internal/flags/source_oci_verify_provider.go
  internal/flags/source_oci_verify_provider_test.go
Labels: area/oci, area/ux
