Repository fluxcd/flux2, pull requests merged in 2023-06, with the labels that each got.

#3945 Make `flux logs` more lenient
  cmd/flux/logs.go
  cmd/flux/logs_e2e_test.go
  cmd/flux/logs_unit_test.go
  cmd/flux/main_test.go
Labels: area/UX

#4008 Add SLSA3 generators to release workflow
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/release.yaml
Labels: area/build, area/security

#3990 RFC-0004: add section about proxy
  rfcs/0004-insecure-http/README.md
Labels: area/RFC

#4015 Align `go.mod` version with Kubernetes (Go 1.20)
  .github/aur/flux-go/PKGBUILD.template
  .github/aur/flux-scm/PKGBUILD.template
  go.mod
  tests/azure/go.mod
Labels: area/build

#4018 docs: Fix the `flux push` example for ECR
  cmd/flux/push_artifact.go
Labels: area/docs, area/oci

#4023 Add backport GitHub Action workflow
  .github/dependabot.yml
  .github/labels.yaml
  .github/workflows/backport.yaml
  .github/workflows/sync-labels.yaml
Labels: area/build
