Repository fluxcd/flux2, pull requests merged in 2023-07, with the labels that each got.

#4027 Update go-git to unreleased v5.8.0
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/git, dependencies

#4028 Annotate errors from go-git-providers
  pkg/bootstrap/bootstrap_provider.go
Labels: area/bootstrap

#3254 Flux GA release spec and long term support pledge
  README.md
  docs/README.md
  docs/_files/gitops-toolkit.png
  docs/_redirects
  docs/internal/diagrams.md
  docs/internal/release.md
  docs/release/README.md
  docs/release/controllers.md
  docs/release/flux.md
  docs/release/packages.md
  docs/release/procedure.md
  docs/release/release-notes-template.md
Labels: area/docs

#4029 Run e2e tests on release branches
  .github/dependabot.yml
  .github/workflows/backport.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
Labels: area/ci

#4031 Run conformance tests for Kubernetes v1.27.3
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
Labels: area/ci

#4035 Update dependencies
  Dockerfile
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: dependencies

#4041 ci: release: disable interpretation backslash esc
  .github/workflows/release.yaml
Labels: area/ci, backport:release/v2.0.x

#4046 ci: backport: set write permissions
  .github/workflows/backport.yaml
Labels: area/ci

#4043 ci: release: extract the image tag from GITHUB_REF
  .github/workflows/release.yaml
Labels: area/ci, backport:release/v2.0.x

#4051 action: use `$RUNNER_TOOL_CACHE`, support MacOS and Windows, validate checksum
  .github/workflows/action.yaml
  action/action.yml
Labels: enhancement, area/ci

#4052 docs: Link to the Flux GitHub Action documentation
  action/README.md
Labels: area/docs

#4062 diff: Take into account the server-side inventory for local Flux Kustomizations
  cmd/flux/build_kustomization_test.go
  internal/build/build.go
  internal/build/build_test.go
  internal/build/diff.go
Labels: area/diff

#4068 Update dependencies
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
Labels: dependencies, backport:release/v2.0.x
