Repository fluxcd/flux2, pull requests merged in 2023-05, with the labels that each got.

#3833 Add OCI provider option to create Helm source command
  cmd/flux/create_source_helm.go
Labels: area/source, area/helm

#3795 Run conformance tests for Kubernetes 1.27
  .github/workflows/e2e-arm64.yaml
Labels: area/build

#3860 e2e: Add summary to Azure Alert
  tests/azure/azure_test.go
Labels: area/build

#3880 Add OSSF Scorecard
  .github/workflows/ossf.yaml
  README.md
Labels: area/build

#3879 Add ResourceQuota for critical pods
  manifests/rbac/kustomization.yaml
  manifests/rbac/resourcequota.yaml
Labels: bug, area/bootstrap, area/install

#3883 e2e: Update dependencies
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#3910 Update Kubernetes to v1.27 and Kustomize to v5.0
  cmd/flux/build_artifact.go
  cmd/flux/diff_artifact.go
  cmd/flux/list_artifact.go
  cmd/flux/pull_artifact.go
  cmd/flux/push_artifact.go
  cmd/flux/tag_artifact.go
  go.mod
  go.sum
  pkg/bootstrap/bootstrap_plain_git.go
  pkg/manifestgen/kustomization/kustomization.go
  pkg/status/status.go
  tests/azure/go.mod
  tests/azure/go.sum
  tests/azure/util_test.go
Labels: dependencies

#3675 feat: add reconcile source chart command
  cmd/flux/reconcile_helmrelease.go
  cmd/flux/reconcile_kustomization.go
  cmd/flux/reconcile_source_chart.go
  cmd/flux/reconcile_with_source.go
  cmd/flux/testdata/helmrelease/reconcile_helmrelease_from_git.golden
Labels: enhancement, area/helm

#3924 Fix break lines in create helmrelease and source
  cmd/flux/create_helmrelease.go
  cmd/flux/create_source_helm.go
Labels: area/docs

#3918 Retry oci push operations
  cmd/flux/push_artifact.go
  go.mod
  go.sum
Labels: area/oci

#3928 Update kubectl to v1.27.2 in flux-cli image
  Dockerfile
Labels: area/build

#3929 Update Git packages
  go.mod
  go.sum
  pkg/bootstrap/bootstrap_plain_git.go
  pkg/manifestgen/install/manifests.go
  tests/azure/azure_test.go
  tests/azure/go.mod
  tests/azure/go.sum
  tests/azure/util_test.go
Labels: dependencies

#3932 Set `controller-runtime` logger to a null logger
  cmd/flux/main.go
  go.mod
Labels: bug

#3938 e2e: Run e2e Azure tests for PRs to main if tests or wofklow changes
  .github/workflows/e2e-azure.yaml
Labels: area/build
