Repository fluxcd/flux2, pull requests merged in 2023-03, with the labels that each got.

#3653 Allow custom annotations to be set when pushing OCI artifacts
  cmd/flux/push_artifact.go
  go.mod
  go.sum
Labels: area/UX, area/oci

#3667 Update helm-controller to v0.31.0
  cmd/flux/create_helmrelease.go
  go.mod
  go.sum
  manifests/bases/helm-controller/kustomization.yaml
  manifests/crds/kustomization.yaml
  tests/azure/go.mod
  tests/azure/go.sum
Labels: area/build

#3670 Update Go to 1.20
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
  CONTRIBUTING.md
  Dockerfile
  Makefile
Labels: area/build

#3669 Update GitHub Action workflows
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
  .goreleaser.yml
  cmd/flux/create_source_oci_test.go
  cmd/flux/helmrelease_test.go
  cmd/flux/kustomization_test.go
  cmd/flux/source_oci_test.go
  cmd/flux/testdata/helmrelease/create_helmrelease_from_git.golden
  cmd/flux/testdata/helmrelease/create_source_git.golden
  cmd/flux/testdata/helmrelease/get_helmrelease_from_git.golden
  cmd/flux/testdata/helmrelease/reconcile_helmrelease_from_git.golden
  cmd/flux/testdata/helmrelease/resume_helmrelease_from_git.golden
  cmd/flux/testdata/kustomization/create_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/create_source_git.golden
  cmd/flux/testdata/kustomization/get_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/reconcile_kustomization_from_git.golden
  cmd/flux/testdata/kustomization/resume_kustomization_from_git.golden
  cmd/flux/testdata/oci/create_source_oci.golden
  cmd/flux/testdata/oci/export.golden
  cmd/flux/testdata/oci/export_with_secret.golden
  cmd/flux/testdata/oci/get_oci.golden
  cmd/flux/testdata/oci/reconcile_oci.golden
  cmd/flux/testdata/oci/resume_oci.golden
  cmd/flux/testdata/trace/deployment.golden
  cmd/flux/testdata/trace/deployment.yaml
  cmd/flux/testdata/trace/helmrelease-oci.yaml
  cmd/flux/testdata/trace/helmrelease.yaml
Labels: area/build

#3673 ci: Use latest available images of kindest/node
  .github/workflows/e2e-arm64.yaml
Labels: area/build

#3674 Update dependencies
  go.mod
  go.sum
  internal/build/diff.go
Labels: area/build

#3628 Add `flux events` command
  cmd/flux/events.go
  cmd/flux/events_test.go
  go.mod
  go.sum
Labels: enhancement, area/UX

#3676 Disable drift detection for kube-prometheus-stack webhooks
  manifests/monitoring/kube-prometheus-stack/release.yaml
Labels: area/monitoring

#3706 build: update `actions/setup-go` in workflows
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
Labels: area/build

#3696 Add retry interval option to create kustomization command
  cmd/flux/create_kustomization.go
Labels: area/kustomization

#3654 Implement `--deploy-token-auth` in GitLab bootstrapping
  cmd/flux/bootstrap_gitlab.go
  go.mod
  go.sum
  pkg/bootstrap/bootstrap_provider.go
Labels: enhancement, area/bootstrap

#3721 fix: Avoid printing an extra newline when exporting resources
  cmd/flux/export.go
  cmd/flux/testdata/create_source_git/export.golden
  cmd/flux/testdata/create_source_helm/https.golden
  cmd/flux/testdata/create_source_helm/oci-with-secret.golden
  cmd/flux/testdata/create_source_helm/oci.golden
  cmd/flux/testdata/export/alert.yaml
  cmd/flux/testdata/export/bucket.yaml
  cmd/flux/testdata/export/git-repo.yaml
  cmd/flux/testdata/export/helm-release.yaml
  cmd/flux/testdata/export/helm-repo.yaml
  cmd/flux/testdata/export/image-policy.yaml
  cmd/flux/testdata/export/image-repo.yaml
  cmd/flux/testdata/export/image-update.yaml
  cmd/flux/testdata/export/ks.yaml
  cmd/flux/testdata/export/provider.yaml
  cmd/flux/testdata/export/receiver.yaml
  cmd/flux/testdata/oci/export.golden
  cmd/flux/testdata/oci/export_with_secret.golden
Labels: area/UX
