Repository fluxcd/flux2, pull requests merged in 2024-02, with the labels that each got.

#4589 Update dependencies
  Dockerfile
  go.mod
  go.sum
  tests/azure/go.mod
  tests/azure/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies, backport:release/v2.2.x

#4610 Fix typo in build.go
  internal/build/build.go
Labels: backport:release/v2.2.x

#4620 Update Equinix ARM64 GitHub runners
  .github/runners/README.md
  .github/runners/prereq.sh
  .github/runners/runner-setup.sh
Labels: area/ci

#4629 Fix a typo in `--force` flag description
  cmd/flux/bootstrap.go
  cmd/flux/install.go
Labels: backport:release/v2.2.x
