Repository fluxcd/flux2, pull requests merged in 2024-03, with the labels that each got.

#4654 Remove deprecated e2e tests
  .github/workflows/e2e-azure.yaml
  Makefile
  tests/azure/README.md
  tests/azure/azure_test.go
  tests/azure/go.mod
  tests/azure/go.sum
  tests/azure/terraform/aks/.terraform.lock.hcl
  tests/azure/terraform/aks/aks.tf
  tests/azure/terraform/aks/azuredevops.tf
  tests/azure/terraform/aks/event-hub.tf
  tests/azure/terraform/aks/keyvault.tf
  tests/azure/terraform/aks/main.tf
  tests/azure/terraform/aks/outputs.tf
  tests/azure/terraform/aks/service-principal.tf
  tests/azure/terraform/aks/shared.tf
  tests/azure/terraform/shared/.terraform.lock.hcl
  tests/azure/terraform/shared/acr.tf
  tests/azure/terraform/shared/keyvault.tf
  tests/azure/terraform/shared/main.tf
  tests/azure/terraform/shared/outputs.tf
  tests/azure/terraform/shared/service-principal.tf
  tests/azure/terraform/shared/variables.tf
  tests/azure/util_test.go
Labels: area/testing, backport:release/v2.2.x

#4666 Mark RFC-0006 as implementable
  rfcs/0006-cdevents/CDEvents-Flux-RFC-Broker.png
  rfcs/0006-cdevents/README.md
Labels: area/rfc

#4657 ci: Include all go modules in snyk testing
  .github/workflows/scan.yaml
Labels: area/ci, backport:release/v2.2.x

#4687 Add permissions required for flow control
  manifests/rbac/controller.yaml
Labels: area/security

#4689 Pin envtest version
  Makefile
Labels: area/testing
