Repository fluxcd/flux2, pull requests merged in 2024-05, with the labels that each got.

#4754 Add `--ssh-hostkey-algos` flag to bootstrap command
  cmd/flux/bootstrap.go
  cmd/flux/bootstrap_git.go
Labels: area/git, area/bootstrap

#4759 Update Helm Source APIs to v1 (GA)
  cmd/flux/create_secret_helm.go
  cmd/flux/create_source_helm.go
  cmd/flux/create_source_oci.go
  cmd/flux/delete_source_helm.go
  cmd/flux/events.go
  cmd/flux/export_source_helm.go
  cmd/flux/get_source_all.go
  cmd/flux/get_source_chart.go
  cmd/flux/get_source_helm.go
  cmd/flux/reconcile_helmrelease.go
  cmd/flux/reconcile_source_chart.go
  cmd/flux/reconcile_source_helm.go
  cmd/flux/reconcile_with_source.go
  cmd/flux/resume_source_chart.go
  cmd/flux/resume_source_helm.go
  cmd/flux/source.go
  cmd/flux/stats.go
  cmd/flux/suspend_source_chart.go
  cmd/flux/suspend_source_helm.go
  cmd/flux/testdata/create_source_helm/https.golden
  cmd/flux/testdata/create_source_helm/oci-with-secret.golden
  cmd/flux/testdata/create_source_helm/oci.golden
  cmd/flux/testdata/export/helm-repo.yaml
  cmd/flux/trace.go
  go.mod
  go.sum
  internal/flags/helm_chart_source.go
  internal/flags/helm_chart_source_test.go
  manifests/bases/kustomize-controller/kustomization.yaml
  manifests/bases/source-controller/kustomization.yaml
  manifests/crds/kustomization.yaml
  pkg/bootstrap/bootstrap.go
  pkg/uninstall/uninstall.go
Labels: area/helm

#4764 ci: Adapt image automation test to v1beta2
  .github/workflows/e2e-bootstrap.yaml
  Makefile
  manifests/scripts/bundle.sh
Labels: area/testing

#4678 Update `ImageUpdateAutomation` API to v1beta2
  cmd/flux/create_image_update.go
  cmd/flux/delete_image_update.go
  cmd/flux/events.go
  cmd/flux/export_image_update.go
  cmd/flux/get_image_all.go
  cmd/flux/get_image_update.go
  cmd/flux/image.go
  cmd/flux/reconcile_image_updateauto.go
  cmd/flux/resume_image_updateauto.go
  cmd/flux/stats.go
  cmd/flux/suspend_image_updateauto.go
  cmd/flux/testdata/export/image-update.yaml
  cmd/flux/testdata/export/objects.yaml
  internal/utils/utils.go
  pkg/uninstall/uninstall.go
  tests/image-automation/auto.yaml
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/image_repo_test.go
  tests/integration/suite_test.go
Labels: area/image-automation

#4768 Improve end-to-end test workflow
  .github/kind/config.yaml
  .github/workflows/e2e.yaml
Labels: area/testing

#4770 Update Flux architecture diagram
  README.md
  docs/diagrams/fluxcd-controllers.png
Labels: area/docs

#4773 Add `(create|delete|export) source chart` commands
  cmd/flux/create_source_chart.go
  cmd/flux/create_source_chart_test.go
  cmd/flux/delete_source_chart.go
  cmd/flux/export_source_chart.go
  cmd/flux/export_test.go
  cmd/flux/testdata/create_source_chart/basic.yaml
  cmd/flux/testdata/create_source_chart/setup-source.yaml
  cmd/flux/testdata/create_source_chart/verify_basic.yaml
  cmd/flux/testdata/create_source_chart/verify_complete.yaml
  cmd/flux/testdata/export/helm-chart.yaml
  cmd/flux/testdata/export/objects.yaml
  internal/flags/local_helm_chart_source.go
Labels: area/helm

#4775 Update `HelmRelease` API to v2 (GA)
  cmd/flux/create_helmrelease.go
  cmd/flux/create_kustomization.go
  cmd/flux/delete_helmrelease.go
  cmd/flux/events.go
  cmd/flux/events_test.go
  cmd/flux/export_helmrelease.go
  cmd/flux/get_all.go
  cmd/flux/get_helmrelease.go
  cmd/flux/helmrelease.go
  cmd/flux/reconcile.go
  cmd/flux/reconcile_helmrelease.go
  cmd/flux/resume_helmrelease.go
  cmd/flux/stats.go
  cmd/flux/suspend_helmrelease.go
  cmd/flux/testdata/export/helm-release.yaml
  cmd/flux/testdata/export/objects.yaml
  cmd/flux/testdata/trace/deployment.yaml
  cmd/flux/testdata/trace/helmrelease-oci.yaml
  cmd/flux/testdata/trace/helmrelease.yaml
  cmd/flux/trace.go
  cmd/flux/trace_test.go
  cmd/flux/tree_kustomization.go
  go.mod
  go.sum
  internal/flags/crds.go
  internal/utils/utils.go
  manifests/bases/helm-controller/kustomization.yaml
  manifests/crds/kustomization.yaml
  pkg/uninstall/uninstall.go
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/oci_test.go
  tests/integration/suite_test.go
Labels: area/helm

#4777 Add k3s to the conformance test suite
  .github/workflows/e2e-k3s.yaml
Labels: area/testing

#4778 tests/integration: Run flux check after installation
  tests/integration/suite_test.go
  tests/integration/util_test.go
Labels: area/testing

#4780 Update helm-controller to v1.0.1
  cmd/flux/create_helmrelease.go
  go.mod
  go.sum
  manifests/bases/helm-controller/kustomization.yaml
  manifests/crds/kustomization.yaml
  tests/integration/go.mod
  tests/integration/go.sum
  tests/integration/oci_test.go
Labels: dependencies

#4781 Set Kubernetes 1.28 as min required version
  Dockerfile
  cmd/flux/check.go
  cmd/flux/testdata/check/check_pre.golden
Labels: dependencies

#4783 ci: Consolidate conformance tests
  .github/workflows/conformance.yaml
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-k3s.yaml
  .github/workflows/e2e-openshift.yaml
Labels: area/testing
