Repository fluxcd/flux2, pull requests merged in 2024-04, with the labels that each got.

#4699 Update dependencies to Go 1.22 and Kubernetes 1.29.3
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e-gcp.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
  .github/workflows/update.yaml
  Makefile
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#4705 Update dependencies to Kustomize v5.4.0
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#4706 Add `--registry-creds` flag to bootstrap and install commands
  .github/workflows/e2e-bootstrap.yaml
  cmd/flux/bootstrap.go
  cmd/flux/bootstrap_bitbucket_server.go
  cmd/flux/bootstrap_git.go
  cmd/flux/bootstrap_gitea.go
  cmd/flux/bootstrap_github.go
  cmd/flux/bootstrap_gitlab.go
  cmd/flux/install.go
  cmd/flux/install_test.go
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_plain_git.go
  pkg/manifestgen/install/options.go
  pkg/manifestgen/sourcesecret/sourcesecret.go
Labels: area/bootstrap, area/install

#4709 Add `--strict-substitute` flag to `flux build ks` and `flux diff ks`
  cmd/flux/build_kustomization.go
  cmd/flux/diff_kustomization.go
  go.mod
  go.sum
  internal/build/build.go
Labels: area/diff

#4717 Set `GOMAXPROCS` and `GOMEMLIMIT` to all Flux controllers
  manifests/bases/helm-controller/patch.yaml
  manifests/bases/image-automation-controller/patch.yaml
  manifests/bases/image-reflector-controller/patch.yaml
  manifests/bases/kustomize-controller/patch.yaml
  manifests/bases/notification-controller/patch.yaml
  manifests/bases/source-controller/patch.yaml
Labels: area/bootstrap, area/install

#4728 bootstrap: Add support for Git HTTP/S authorization header
  cmd/flux/bootstrap_git.go
Labels: area/bootstrap

#4727 Add flags for issuer/subject OCI signature verification
  cmd/flux/create_source_oci.go
  cmd/flux/create_source_oci_test.go
  cmd/flux/testdata/oci/export_with_complete_verification.golden
  cmd/flux/testdata/oci/export_with_issuer.golden
  cmd/flux/testdata/oci/export_with_subject.golden
Labels: enhancement, area/source, area/oci

#4729 Add OpenShift to the conformance test suite
  .github/workflows/e2e-openshift.yaml
  manifests/openshift/kustomization.yaml
  manifests/openshift/labels.yaml
  manifests/openshift/namespace.yaml
  manifests/openshift/scc.yaml
Labels: area/bootstrap, area/testing

#4735 feat(secret): add create notation secret handler
  cmd/flux/create_secret_notation.go
  cmd/flux/create_secret_notation_test.go
  cmd/flux/testdata/create_secret/notation/invalid-trust-policy.json
  cmd/flux/testdata/create_secret/notation/invalid.json
  cmd/flux/testdata/create_secret/notation/secret-ca-crt.yaml
  cmd/flux/testdata/create_secret/notation/secret-ca-multi.yaml
  cmd/flux/testdata/create_secret/notation/secret-ca-pem.yaml
  cmd/flux/testdata/create_secret/notation/test-ca.crt
  cmd/flux/testdata/create_secret/notation/test-ca2.crt
  cmd/flux/testdata/create_secret/notation/test-trust-policy.json
  go.mod
  go.sum
  pkg/manifestgen/sourcesecret/options.go
  pkg/manifestgen/sourcesecret/sourcesecret.go
Labels: area/ux

#4746 Specifying go version in setup-go github action.
  .github/workflows/e2e-arm64.yaml
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e-gcp.yaml
  .github/workflows/e2e-openshift.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/update.yaml
Labels: area/ci

#4747 Update dependencies to Kubernetes 1.30
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies
