Repository fluxcd/flux2, pull requests merged in 2024-01, with the labels that each got.

#4553 Properly detect unexpected arguments during uninstall
  cmd/flux/uninstall.go
Labels: area/install, backport:release/v2.2.x

#4557 `flux stats` should error on unrecognised args
  cmd/flux/stats.go
Labels: backport:release/v2.2.x

#4558 `flux check` should error on unrecognised args
  cmd/flux/check.go
Labels: backport:release/v2.2.x

#4575 Update dependencies to Kubernetes v1.28.6
  cmd/flux/build_kustomization.go
  cmd/flux/cluster_info_test.go
  cmd/flux/events_test.go
  cmd/flux/tree_kustomization.go
  go.mod
  go.sum
  internal/build/build.go
  internal/build/diff.go
  internal/tree/tree.go
  internal/utils/apply.go
  tests/azure/go.mod
  tests/azure/go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies, backport:release/v2.2.x
