Repository fluxcd/flux2, pull requests merged in 2024-08, with the labels that each got.

#4892 Run conformance tests for Kubernetes v1.31
  .github/workflows/conformance.yaml
Labels: area/testing

#4934 Update dependencies to Kubernetes v1.31.0
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#4936 Build with Go 1.23
  .github/workflows/e2e-azure.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e-gcp.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/update.yaml
  Dockerfile
Labels: area/ci

#4948 fix: fixed GHA token-permission and pinned dependencies issue
  .github/workflows/backport.yaml
  .github/workflows/conformance.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  .github/workflows/scan.yaml
Labels: area/ci
