Repository fluxcd/flux2, pull requests merged in 2025-02, with the labels that each got.

#5175 Update dependencies
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#5176 fix: align `flux diff` skipping with kustomize-controller
  internal/build/diff.go
Labels: area/diff

#5187 Update conformance test suite
  .github/workflows/conformance.yaml
Labels: area/testing

#5103 [RFC-007] Flux cli support for GitHub app authentication
  cmd/flux/create_secret_github_app.go
  cmd/flux/create_secret_githubapp_test.go
  cmd/flux/create_source_git.go
  cmd/flux/create_source_git_test.go
  cmd/flux/testdata/create_secret/githubapp/secret-with-baseurl.yaml
  cmd/flux/testdata/create_secret/githubapp/secret.yaml
  cmd/flux/testdata/create_secret/githubapp/test-private-key.pem
  cmd/flux/testdata/create_source_git/source-git-provider-github.yaml
  go.mod
  internal/flags/source_git_provider.go
  pkg/manifestgen/sourcesecret/options.go
  pkg/manifestgen/sourcesecret/sourcesecret.go
Labels: hold

#5199 Update integration tests dependencies for Flux 2.5
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#5215 Update backport labels for 2.5
  .github/labels.yaml
Labels: area/ci
