Repository fluxcd/flux2, pull requests merged in 2025-05, with the labels that each got.

#5332 [RFC-0010] Add RBAC for creating service account tokens
  manifests/rbac/controller.yaml
Labels: area/security

#5333 Upgrade fluxcd/pkg auth, oci, git and git/gogit
  cmd/flux/build_artifact.go
  cmd/flux/diff_artifact.go
  cmd/flux/list_artifact.go
  cmd/flux/pull_artifact.go
  cmd/flux/push_artifact.go
  cmd/flux/tag_artifact.go
  go.mod
  go.sum
  internal/flags/source_oci_provider.go
Labels: dependencies

#5351 Fix e2e workflow
  .github/workflows/e2e.yaml
Labels: area/ci

#5356 Upgrade fluxcd/pkg packages
  go.mod
  go.sum
Labels: dependencies

#5357 Upgrade fluxcd/pkg packages
  cmd/flux/diff_artifact.go
  cmd/flux/list_artifact.go
  cmd/flux/oci.go
  cmd/flux/pull_artifact.go
  cmd/flux/push_artifact.go
  cmd/flux/tag_artifact.go
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#5364 Set Kubernetes 1.31 as min supported version
  .github/workflows/conformance.yaml
  .github/workflows/e2e-bootstrap.yaml
  .github/workflows/e2e.yaml
  cmd/flux/check.go
  cmd/flux/testdata/check/check_pre.golden
Labels: area/testing

#5366 Update dependencies
  go.mod
  go.sum
  tests/integration/go.mod
  tests/integration/go.sum
Labels: dependencies

#5369 Promote artifact commands to stable
  cmd/flux/build_artifact.go
  cmd/flux/diff_artifact.go
  cmd/flux/list_artifact.go
  cmd/flux/pull_artifact.go
  cmd/flux/push_artifact.go
  cmd/flux/tag_artifact.go
Labels: area/oci

#5345 Add --interval and --reflect-digest flags to flux create image policy
  cmd/flux/create_image_policy.go
  cmd/flux/image_test.go
  cmd/flux/testdata/image/get_image_policy_semver.golden
Labels: area/image-automation

#5371 Update CLI to OCIRepository v1 (GA)
  cmd/flux/create_helmrelease.go
  cmd/flux/create_source_oci.go
  cmd/flux/delete_source_chart.go
  cmd/flux/delete_source_oci.go
  cmd/flux/diff_artifact.go
  cmd/flux/events.go
  cmd/flux/export_source_oci.go
  cmd/flux/get_source_all.go
  cmd/flux/get_source_oci.go
  cmd/flux/list_artifact.go
  cmd/flux/pull_artifact.go
  cmd/flux/push_artifact.go
  cmd/flux/reconcile_helmrelease.go
  cmd/flux/reconcile_kustomization.go
  cmd/flux/reconcile_source_oci.go
  cmd/flux/resume_source_oci.go
  cmd/flux/source.go
  cmd/flux/stats.go
  cmd/flux/suspend_source_oci.go
  cmd/flux/tag_artifact.go
  cmd/flux/testdata/create_hr/setup-source.yaml
  cmd/flux/testdata/oci/export.golden
  cmd/flux/testdata/oci/export_with_complete_verification.golden
  cmd/flux/testdata/oci/export_with_issuer.golden
  cmd/flux/testdata/oci/export_with_secret.golden
  cmd/flux/testdata/oci/export_with_subject.golden
  cmd/flux/testdata/oci/export_with_verify_secret.golden
  cmd/flux/testdata/trace/deployment-hr-ocirepo.yaml
  cmd/flux/testdata/trace/helmrelease-oci.yaml
  cmd/flux/trace.go
  internal/flags/kustomization_source.go
  internal/flags/source_oci_provider.go
  internal/utils/utils.go
  pkg/bootstrap/bootstrap.go
  pkg/bootstrap/bootstrap_test.go
  pkg/uninstall/uninstall.go
  tests/integration/suite_test.go
Labels: area/oci
