Repository fluxcd/flux2, pull requests merged in 2025-06, with the labels that each got.

#5379 Add backport label for `v2.6.x`
  .github/labels.yaml
Labels: area/ci

#5390 fix: Allow Azure CLI calls in `flux push artifact --provider azure` on DevOps runners
  cmd/flux/oci.go
  cmd/flux/push_artifact.go
  go.mod
  go.sum
Labels: area/oci, backport:release/v2.6.x

#5402 Make service-account name configurable in `flux create tenant`
  cmd/flux/create_tenant.go
  cmd/flux/create_tenant_test.go
  cmd/flux/testdata/create_tenant/tenant-basic.yaml
  cmd/flux/testdata/create_tenant/tenant-with-cluster-role.yaml
  cmd/flux/testdata/create_tenant/tenant-with-service-account.yaml
Labels: area/ux
